.TH M2EE 1 "April 2011" "" "Mendix 2.5"
.nh
.ad l

.SH NAME
m2ee \- mendix 2.5 deployment tool

.SH SYNOPSIS
.HP \w'm2ee\ 'u
m2ee [ \fIoptions\fR ] [ \fIaction\fR ]

.SH DESCRIPTION
\fBm2ee\fR provides an interactive way to manage a Mendix Business Server process.

.SH OPTIONS
.PP
\fB\-c \fR\fB\fIconfigfile\fR\fR
.RS 4
Use a specific configuation file instead of searching for default configuration 
files (/etc/m2ee/m2ee\&.yaml and ~/\&.m2ee/m2ee\&.yaml)\&. This option can be specified multiple times\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increase verbosity of output. (\-vv to be even more verbose)
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Decrease verbosity of output (\-qq to be even more quiet)
.RE
.SH "SEE ALSO"
.B
Online documentation:
http://link-to-wiki
