#!/usr/bin/python3
import pwd
import os
import sys
import logging
import m2ee

logger = logging.getLogger()
logger.setLevel(logging.WARNING)
consolelogformatter = logging.Formatter("%(levelname)s: %(message)s")
stderrlog = logging.StreamHandler(sys.stderr)
stderrlog.setFormatter(consolelogformatter)
logger.addHandler(stderrlog)

try:
    command = sys.argv[1]
except IndexError:
    command = 'values'

if command == 'autoconf':
    print("no")
else:
    name = pwd.getpwuid(os.getuid())[0]
    m2ee_instance = m2ee.M2EE()
    if command == 'config':
        m2ee.munin.print_config(m2ee_instance, name)
    else:
        m2ee.munin.print_values(m2ee_instance, name)
