#!/usr/bin/python
import pwd
import os
import sys
import m2ee

m2ee.logger.setLevel(51)

try:
    command = sys.argv[1]
except IndexError:
    command = 'values'

if command == 'autoconf':
    print("no")
else:
    name = pwd.getpwuid(os.getuid())[0]
    m2ee_instance = m2ee.M2EE()
    if command == 'config':
        m2ee.munin.print_config(m2ee_instance, name)
    else:
        m2ee.munin.print_values(m2ee_instance, name)
